### PR TITLE
Add a linter for hardcoded IDs in specs

### PR DESCRIPTION
**Pull request by rzane**
Hardcoded IDs lead to flaky specs. This PR adds a rule that will report the following offenses:

```ruby
FactoryBot.create(:employee, id: 99)
FactoryBot.create(:employee, employer_id: 99)
```

It can also detect when an ID is hardcoded in a `let` and passed to a factory:

```ruby
let(:employee_id) { 99 }
let(:employee) { FactoryBot.create(:employee, id: employee_id) }
```

## Correction

Most of the complexity here is related to correcting these sorts of offenses. These violations can't be corrected reliably 100% of the time, but it does work for the vast majority of cases.

Because correction isn't 100% reliable, autocorrection is disabled by default. That way, if someone is on a mission to fix these offenses, they can temporarily enable autocorrection.

Correction is only possible when:
* The offense is registered for the ID attribute. We know that the database will generate this value, and that it will never be nil if `FactoryBot.create` succeeds. Foreign IDs (e.g. `employer_id`) can't be autocorrected.
* The offense occurs within a let.
* References to the hardcoded ID will be updated, but only if they occur within a block. That means if you pass a URL containing a hardcoded ID to `include_examples`, the URL won't be updated.

Here's what correction looks like:

#### Before

```ruby
let(:employee_id) { 99 }
let(:employee) { FactoryBot.create(:employee, id: employee_id) }

it "generates a URL" do
  expect(employee_path(employee)).to eq("/employees/99")
end
```

#### After
```ruby
let(:employee_id) { employee.id }
let(:employee) { FactoryBot.create(:employee) }

it "generates a URL" do
  expect(employee_path(employee)).to eq("/employees/#{employee.id}")
end
```

### CODE REVIEW

**Review by kellyi — APPROVED** [review]
<< domainLGTM!

**Review by smudge — CHANGES_REQUESTED** [review]
domain TAFN - this is great! My only request would be an update to the `README` that explains the usage and points out that you can set `AutoCorrect: true` in your app if you want to try it out!

**Review by smudge — APPROVED** [review]
platform LGTM!

**Review by smudge — APPROVED** [review]
domain LGTM as well (oops)

**Review by smudge — APPROVED** [review]
domain LGTM

**Pull request merged**
