### PR TITLE
Fix dependabot Workflow

### PR DESCRIPTION
**Pull request by lindan-betterment**
/domain @smudge 
/platform @Betterment/security 

/task https://app.asana.com/0/1200240516476402/1200218309280850/f

The dependabot workflow has been failing due to [changes in dependabot's PR permissions](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/). This change uses `pull_request_target` to give PR write permissions to dependabot.

### CODE REVIEW

**Comment by lindan-betterment** [comment]
Why are the checks failing even though I changed no Ruby files?

**Comment by smudge** [comment]
> Why are the checks failing even though I changed no Ruby files?

@lindan-betterment It looks like Rubocop added a new rule that got picked up in the build. You can run the following command to ignore the issues:

```
rubocop --auto-gen-config --auto-gen-only-exclude --exclude-limit 99999
```

Or you can run the following command to correct the issues:

```
rubocop --auto-correct
```

I'd start with the latter, and if the build passes, then you're good 👍

**Comment by lindan-betterment** [comment]
> > Why are the checks failing even though I changed no Ruby files?
> 
> @lindan-betterment It looks like Rubocop added a new rule that got picked up in the build. You can run the following command to ignore the issues:
> 
> ```
> bundle exec rubocop --auto-gen-config --auto-gen-only-exclude --exclude-limit 99999
> ```
> 
> Or you can run the following command to correct the issues:
> 
> ```
> bundle exec rubocop --auto-correct
> ```
> 
> I'd start with the latter, and if the build passes, then you're good 👍

Got it, it ended up correcting a spec file. Thanks!

**Comment by smudge** [comment]
<< domain LGTM!

**Comment by lindan-betterment** [comment]
@lindan-betterment << platform

**Pull request merged**
